---
galaxy_info:
  author: Leo
  description: AWS Cloud Lab Infrastructure
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all

dependencies: []

collections:
  - amazon.aws
  - community.aws 