apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: discoverlocal
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-service
  namespace: discoverlocal
subsets:
- addresses:
  - ip: 192.168.1.200  # Host machine IP where Docker redis is exposed on port 6379
  ports:
  - port: 6379
    protocol: TCP