---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: l3o
    ansible_ssh_private_key_file: ~/.ssh/leo-personal

  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
    
    homelab:
      children:
        high_resource:
          hosts:
            alef:
              ansible_host: 192.168.1.10
              ansible_user: admin
              node_type: server
              services:
                - prometheus
                - grafana
                - loki
                - ollama
                - librechat
                - jitsi
        
        medium_resource:
          hosts:
            bet:
              ansible_host: 192.168.1.11
              ansible_user: admin
              node_type: server
              services:
                - syncthing
                - rustdesk
                - coolify
        
            gimel:
              ansible_host: 192.168.1.12
              ansible_user: admin
              node_type: server
              services:
                - matrix
                - vaultwarden
                - n8n
        
        low_resource:
          hosts:
            dalet:
              ansible_host: 192.168.1.13
              ansible_user: admin
              node_type: pi
              services:
                - traefik
                - hickory_dns
                - node_exporter
        
            he:
              ansible_host: 192.168.1.14
              ansible_user: admin
              node_type: pi
              services:
                - authelia
                - fail2ban
                - ufw
        
        main_server:
          hosts:
            alef:
              ansible_host: 192.168.1.200
              ansible_port: 22
              # Server specifications
              ram_gb: 55
              storage_gb: 3000
              cpu_cores: 8
        
        # Distributed services across Pi cluster
        dns_nodes:
          vars:
            dns_role: secondary
            route53_integration: true
          hosts:
            legion001:
              ansible_host: 192.168.1.201
              dns_role: primary
            legion002:
              ansible_host: 192.168.1.202
            legion003:
              ansible_host: 192.168.1.203
            legion004:
              ansible_host: 192.168.1.204
            legion005:
              ansible_host: 192.168.1.205
        
        monitoring_nodes:
          vars:
            node_exporter_enabled: true
            prometheus_retention: 15d
          hosts:
            legion006:
              ansible_host: 192.168.1.206
            legion007:
              ansible_host: 192.168.1.207
            legion008:
              ansible_host: 192.168.1.208
            legion009:
              ansible_host: 192.168.1.209
            legion010:
              ansible_host: 192.168.1.210

        storage_nodes:
          vars:
            syncthing_enabled: true
            min_free_space: "2GB"
          hosts:
            legion011:
              ansible_host: 192.168.1.211
              storage_gb: 64
            legion012:
              ansible_host: 192.168.1.212
              storage_gb: 64
            legion013:
              ansible_host: 192.168.1.213
              storage_gb: 32
            legion014:
              ansible_host: 192.168.1.214
              storage_gb: 16

        edge_nodes:
          vars:
            traefik_enabled: true
            cloudflare_integration: true
          hosts:
            legion015:
              ansible_host: 192.168.1.215
            legion016:
              ansible_host: 192.168.1.216
            legion019:
              ansible_host: 192.168.1.219

        legion_cluster:
          vars:
            ansible_user: l3o
            ansible_ssh_private_key_file: ~/.ssh/leo-personal
            ram_gb: 1
            max_storage_gb: 64
            cpu_cores: 4
          hosts:
            legion020:
              ansible_host: 192.168.1.220
            legion021:
              ansible_host: 192.168.1.221
            legion022:
              ansible_host: 192.168.1.222
            legion024:
              ansible_host: 192.168.1.224
            legion028:
              ansible_host: 192.168.1.228
            legion029:
              ansible_host: 192.168.1.229
            legion031:
              ansible_host: 192.168.1.231
            legion034:
              ansible_host: 192.168.1.234
            legion035:
              ansible_host: 192.168.1.235
            legion036:
              ansible_host: 192.168.1.236
            legion037:
              ansible_host: 192.168.1.237
            legion038:
              ansible_host: 192.168.1.238
            legion040:
              ansible_host: 192.168.1.240
        other_devices:
          hosts:
            raspberrypi:
              ansible_host: 192.168.1.181
              ansible_user: pi

    aws_integration:
      vars:
        route53_enabled: true
        aws_region: us-east-1
        # Use existing AWS profiles
        aws_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default') }}"
        aws_assume_role: false
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        aws_session_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default(omit) }}"
      children:
        primary_zone:
          hosts:
            alef:
              route53_role: primary
              domains:
                - name: homelab.internal
                  zone_id: "{{ route53_zone_id }}"
                  aws_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default') }}"
        secondary_zones:
          vars:
            aws_profile: "{{ lookup('env', 'AWS_PROFILE') | default('default') }}"
          hosts:
            legion001:
            legion015:
            legion016:

    coolify_managed:
      vars:
        coolify_enabled: true
        coolify_api_key: "{{ lookup('env', 'COOLIFY_API_KEY') }}"
        coolify_url: "https://{{ lookup('env', 'COOLIFY_DOMAIN') }}"
      children:
        primary_controller:
          hosts:
            alef:
              coolify_role: server
        worker_nodes:
          hosts:
            legion001:
            legion002:
            legion003:
