---
# handlers file for roles/service-template

# Handlers for service management

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: restart service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  become: true

- name: reload service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: reloaded
  become: true
