http:
  middlewares:
    # Authelia ForwardAuth
    authelia:
      forwardAuth:
        address: 'http://authelia-leopaska:9091/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - 'Remote-User'
          - 'Remote-Groups'
          - 'Remote-Email'
          - 'Remote-Name'
    
    # Basic Authentication (for services that bypass Authelia)
    basic-auth:
      basicAuth:
        users:
          - "lpask001:$apr1$zSMMUBei$9/FoQeRLljnY39Hp6tMPY/"
        realm: "Leopaska Homelab"
    
    # Basic auth that allows static assets
    basic-auth-smart:
      basicAuth:
        users:
          - "lpask001:$apr1$zSMMUBei$9/FoQeRLljnY39Hp6tMPY/"
        realm: "Leopaska Homelab"
        removeHeader: true
    
    # Rate limiting
    api-rate-limit:
      rateLimit:
        burst: 100
        average: 50
    
    admin-rate-limit:
      rateLimit:
        burst: 20
        average: 10
    
    # Security headers
    security:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    
    # Local network only access
    local-only:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
    
    # HTTPS redirect
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
