[global]
server_name = "${DOMAIN}"
database_backend = "rocksdb"
database_path = "/var/lib/matrix-conduit/conduit_db"
allow_registration = false
allow_federation = true
max_request_size = 20000000
trusted_servers = ["matrix.org"]

[listener]
address = "0.0.0.0"
port = 6167 