---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    cgroupns_mode: host
  - name: instance-wsl
    image: mcr.microsoft.com/windows/wsl:ubuntu-22.04
    pre_build_image: false
    command: ""
    privileged: true
  - name: instance-macos
    image: sickcodes/docker-osx:monterey
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_user: root
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
