[http.middlewares]
  [http.middlewares.https-redirect.redirectscheme]
    scheme = "https"
    permanent = true 

# Add global HTTP to HTTPS redirect for all web entrypoint traffic
[http.routers]
  [http.routers.http-to-https]
    entrypoints = ["web"]
    rule = "HostRegexp(`{host:.+}`)"
    middlewares = ["https-redirect"]
    service = "noop@internal"
    priority = 1

[http.services]
  [http.services.noop.loadbalancer]
    [[http.services.noop.loadbalancer.servers]]
      url = "http://localhost:9999"  # This is a dummy service that won't be used 