tunnel: 8a8129e7-f8c3-4cc4-8b1f-9995da97fff0
credentials-file: /home/l3o/git/homelab/services/cloudflare-tunnel/credentials.json

# Template for homelab services - variables will be substituted
ingress:
  # === K3S SERVICES (Route to K3s Traefik) ===
  
  # ArgoCD (K3s GitOps)
  - hostname: argocd.leopaska.xyz
    service: http://192.168.1.200:32251
    originRequest:
      httpHostHeader: argocd.leopaska.xyz

  # Localist AI (K3s Production App)  
  - hostname: localist.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: localist.leopaska.xyz

  # K3s-specific monitoring services
  - hostname: grafana-k3s.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: grafana-k3s.leopaska.xyz

  - hostname: prometheus-k3s.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: prometheus-k3s.leopaska.xyz

  - hostname: traefik-k3s.leopaska.xyz
    service: http://localhost:30808
    originRequest:
      httpHostHeader: traefik-k3s.leopaska.xyz

  # === DOCKER SERVICES (Route to Docker Traefik) ===
  
  # Main homelab dashboard (Docker Traefik)
  - hostname: traefik.leopaska.xyz
    service: http://localhost:8080
    originRequest:
      httpHostHeader: traefik.leopaska.xyz

  # Infrastructure monitoring (via Docker Traefik)
  - hostname: grafana.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: grafana.leopaska.xyz

  - hostname: prometheus.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: prometheus.leopaska.xyz
  - hostname: uptimekuma.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: uptimekuma.leopaska.xyz

  - hostname: loki.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: loki.leopaska.xyz

  - hostname: nodeexporter.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: nodeexporter.leopaska.xyz

  # === PRODUCTIVITY & AUTOMATION ===
  
  - hostname: n8n.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: n8n.leopaska.xyz

  - hostname: coolify.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: coolify.leopaska.xyz

  - hostname: homeassistant.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: homeassistant.leopaska.xyz

  - hostname: huginn.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: huginn.leopaska.xyz

  - hostname: postiz.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: postiz.leopaska.xyz

  # === AI/ML SERVICES ===
  
  - hostname: ollama.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: ollama.leopaska.xyz

  - hostname: librechat.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: librechat.leopaska.xyz

  - hostname: openwebui.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: openwebui.leopaska.xyz

  - hostname: umami.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: umami.leopaska.xyz

  # === STORAGE & DATA ===
  
  - hostname: minio.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: minio.leopaska.xyz

  - hostname: whodb.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: whodb.leopaska.xyz

  - hostname: pgadmin.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: pgadmin.leopaska.xyz

  - hostname: adminer.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: adminer.leopaska.xyz

  - hostname: syncthing.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: syncthing.leopaska.xyz

  - hostname: spacedrive.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: spacedrive.leopaska.xyz

  # === COMMUNICATION ===
  
  - hostname: conduit.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: conduit.leopaska.xyz

  - hostname: element.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: element.leopaska.xyz

  - hostname: rustpad.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: rustpad.leopaska.xyz

  - hostname: mailhog.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: mailhog.leopaska.xyz

  # === MEDIA & CONTENT ===
  
  - hostname: jellyfin.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: jellyfin.leopaska.xyz

  # === INFRASTRUCTURE ===
  
  - hostname: rabbitmq.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: rabbitmq.leopaska.xyz

  # === SECURITY & AUTH ===
  
  - hostname: authelia.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: authelia.leopaska.xyz

  - hostname: vaultwarden.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: vaultwarden.leopaska.xyz

  # === REMOTE ACCESS ===

  - hostname: rustdesk.leopaska.xyz
    service: http://localhost:80
    originRequest:
      httpHostHeader: rustdesk.leopaska.xyz

  # === INFRASTRUCTURE SERVICES (K3S) ===
  
  # IPFS Gateway
  - hostname: ipfs.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: ipfs.leopaska.xyz

  # RTMP Streaming Ingestion (for streamers publishing)
  - hostname: rtmp.leopaska.xyz
    service: tcp://localhost:31935
    originRequest:
      noTLSVerify: true

  # HLS Playback (for viewers watching)
  - hostname: live.leopaska.xyz
    service: http://localhost:30880
    originRequest:
      httpHostHeader: live.leopaska.xyz

  # === PRODUCTION APPLICATIONS (K3S) ===
  
  # American Enlightenment
  - hostname: ae.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: ae.leopaska.xyz

  # Potluck Pub
  - hostname: potluck.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: potluck.leopaska.xyz

  # TheBlink Live
  - hostname: blink.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: blink.leopaska.xyz

  # HyvaPaska
  - hostname: hyva.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: hyva.leopaska.xyz

  # Ursulai
  - hostname: ursulai.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: ursulai.leopaska.xyz

  # OmniLemma
  - hostname: omni.leopaska.xyz
    service: http://localhost:30080
    originRequest:
      httpHostHeader: omni.leopaska.xyz

  # Catch-all rule (must be last)
  - service: http_status:404
