---
# Tasks for service installation and configuration

- name: Install required packages
  ansible.builtin.package:
    name: "{{ service_packages }}"
    state: present
  become: true

- name: Create service user
  ansible.builtin.user:
    name: "{{ service_user }}"
    system: yes
    create_home: yes
    home: "{{ service_home }}"
  become: true

- name: Create service directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0755'
  loop:
    - "{{ service_config_dir }}"
    - "{{ service_data_dir }}"
    - "{{ service_log_dir }}"
  become: true

- name: Configure service
  ansible.builtin.template:
    src: service.conf.j2
    dest: "{{ service_config_file }}"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  notify: restart service
  become: true

- name: Install systemd service file
  ansible.builtin.template:
    src: service.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: 
    - reload systemd
    - restart service
  become: true

- name: Enable and start service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
  become: true
