---
server:
  address: 'tcp://:9091'

log:
  level: debug
  file_path: /config/authelia.log

theme: light

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Add identity_validation section to replace deprecated jwt_secret
identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    # Public access to the authentication portal - both remote and local
    - domain: 
        - auth.codeofconsciousness.com
        - auth.localhost
        - auth.lan
        - 192.168.0.0/16
        - 10.0.0.0/8
        - 172.16.0.0/12
      policy: bypass
    # Admin access to all domains
    - domain: 
        - '*.codeofconsciousness.com'
        - '*.localhost'
        - '*.lan'
        - '192.168.0.0/16'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
      subject: 'group:admins'
      policy: one_factor
    # User access to all domains
    - domain: 
        - '*.codeofconsciousness.com'
        - '*.localhost'
        - '*.lan'
        - '192.168.0.0/16'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
      subject: 'group:users'
      policy: one_factor
    # API access
    - domain: 
        - '*.codeofconsciousness.com'
        - '*.localhost'
        - '*.lan'
        - '192.168.0.0/16'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
      resources:
        - '^/api([/?].*)?$'
      policy: one_factor

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  same_site: lax
  remember_me: 1M
  redis:
    host: redis-nd-codeofconsciousness
    port: 6379
    password: ${REDIS_PASSWORD}
    database_index: 0
  cookies:
    # Remote domain
    - domain: codeofconsciousness.com
      authelia_url: https://auth.codeofconsciousness.com
      default_redirection_url: https://chat.codeofconsciousness.com
    # Local domains - Using https for everything
    - domain: localhost.local
      authelia_url: https://auth.localhost.local
      default_redirection_url: https://chat.localhost.local
      insecure_cookie: true
    # IP-based access - we need separate entries for common private IP ranges
    - domain: 127.0.0.1
      authelia_url: https://127.0.0.1:9091
      default_redirection_url: https://127.0.0.1:8080
      insecure_cookie: true
    # 192.168.x.x range
    - domain: 192.168.1.1
      authelia_url: https://192.168.1.1:9091
      default_redirection_url: https://192.168.1.1:8080
      insecure_cookie: true
    # Additional common IP patterns
    - domain: 10.0.0.1
      authelia_url: https://10.0.0.1:9091
      default_redirection_url: https://10.0.0.1:8080
      insecure_cookie: true
    - domain: 172.16.0.1
      authelia_url: https://172.16.0.1:9091
      default_redirection_url: https://172.16.0.1:8080
      insecure_cookie: true

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  postgres:
    address: tcp://neon-postgres:5432
    database: authelia
    username: postgres
    password: ${POSTGRES_PASSWORD}

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
