---
server:
  address: 'tcp://:9091'

log:
  level: info

theme: light

totp:
  issuer: authelia.com
  period: 30
  skew: 1

identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: one_factor

session:
  secret: ${AUTHELIA_SESSION_SECRET}
  name: authelia_session
  expiration: 3600
  inactivity: 300
  same_site: lax
  remember_me: 1M
  redis:
    host: redis-nd-leopaska
    port: 6379
    password: ${REDIS_PASSWORD}
    database_index: 0
  cookies:
    - domain: leopaska.com
      authelia_url: https://auth.leopaska.com
      default_redirection_url: https://chat.leopaska.com
    - domain: localhost
      authelia_url: http://localhost:9091
      default_redirection_url: http://localhost:8080

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  postgres:
    address: tcp://neon-postgres:5432
    database: authelia
    username: postgres
    password: ${POSTGRES_PASSWORD}

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt