---
# Check for Homebrew
- name: Check if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not homebrew_check.stat.exists

- name: Install essential tools
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    upgrade_all: no
  with_items:
    - git
    - curl
    - wget
    - python@3.13
    - ansible
