data_dir: /var/lib/vector

api:
  enabled: true
  address: 0.0.0.0:8686

sources:
  docker_logs:
    type: docker_logs
    include_images: ["*"]
    docker_host: unix:///var/run/docker.sock

transforms:
  parse_logs:
    type: remap
    inputs: [docker_logs]
    source: |
      . = parse_json!(.message)

sinks:
  console:
    type: console
    inputs: [parse_logs]
    encoding:
      codec: json

  file:
    type: file
    inputs: [parse_logs]
    path: /var/lib/vector/logs/system_logs.json
    encoding:
      codec: json 